name: Readoscope
favicon: null
layout_spectrum: 0.003804923966526985
typography_spectrum: 0.4470606269314885
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9822968090884387
  lightness: 0.41014984576031566
  saturation: 0.7802163541782647
  rhythmicContrast: 0.9355901111848652
purpose: []
